# 002_cifar_debug.yaml
model: wresnet_4_1
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 5
method:
  base: uda  # sup, ra, uda
  is_mpl: True
optim:
  lb_smooth: 0.1
comm:
  n_steps: 60
  n_warmup: 10
batch_size:
  sup: 128
  uns: 128
  test: 128
stdn:
  lr: 0.3
  dropout: 0.35
tchr:
  lr: 0.125
  dropout: 0.5
uda:
  factor: 1.0
  tsa_schedule: 'linear'  # ['', ''linear', 'log', 'exp']  # for labeled loss
  confid_threshold: 0.8   # for unlabeled target dist.
  softmax_temp: 0.4       # for unlabeled predicted dist.
randaug:
  n: 3
  m: 4
tune:
  stdn.lr: [0.001, 1.0]
  tchr.lr: [0.001, 1.0]
  stdn.dropout: [0, 1]
  tchr.dropout: [0, 1]
  optim.momentum: [0.5, 0.999]
  # batch_size.sup: [64, 512]
  comm.w_decay: [0.001, 0.00001]
  comm.bn_decay: [0, 1]
  uda.factor: [0, 10]
  uda.confid_threshold: [0, 1]
  uda.softmax_temp: [0, 1]
