model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1 # in ['top1', 'loss']
  interval: 100
method:
  ##############
  base: uda  # sup, ra, uda
  ##############
  mpl: False
optim:
  name: sgd
  nesterov: True
  momentum: 0.9
  lb_smooth: 0.0
aug:
  default: True
  cutout: 16
comm:
  w_decay: 0.0005
  bn_decay: 0.99
  n_steps: 1000000  # 500k in the official code
  n_warmup: 2000
batch_size:
  sup: 64   # 64
  uns: 448  # 64 * 7 (updated in the official code on 3 Feb)
  test: 10000
stdn:
  lr: 0.03
  dropout: 0.0  # no dropout
uda:
  factor: 1.0
  tsa_schedule: 'linear'  # ['', ''linear', 'log', 'exp']  # for labeled loss
  confid_threshold: 0.8   # for unlabeled target dist.
  softmax_temp: 0.4       # for unlabeled predicted dist.
randaug:
  n: 3
  m: 4
