model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1 # in ['top1', 'loss']
  interval: 100
method:
  ##############
  base: uda  # sup, ra, uda
  ##############
  mpl: False
optim:
  name: sgd
  nesterov: True
  momentum: 0.9
  lb_smooth: 0.0
aug:
  default: True
  cutout: 16
comm:
  w_decay: 0.0005
  bn_decay: 0.99
  n_steps: 1000000
  n_warmup: 2000
batch_size:
  sup: 128  # 64
  uns: 128  # 320
  test: 128
stdn:
  lr: 0.3
  batch: 128
  dropout: 0.35
tchr:
  lr: 0.125
  batch: 128  # 320 when uda
  dropout: 0.5
uda:
  on: True
  factor: 1.0
  temp: 0.8
randaug:
  n: 3
  m: 5
