# 003_cifar_label_smoothing
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 500
method:
  base: sup
  mpl: False
optim:
  name: sgd
  nesterov: True
  momentum: 0.9
  lb_smooth: 0.1
  clip_grad: 5.0
batch_size:
  sup: 128
  # uns: 128
  test: 128
stdn:
  lr: 0.3
  dropout: 0.35
tune:
  stdn.lr: [0.0001, 1.0]
  stdn.dropout: [0, 0.5]
  batch_size.sup: [64, 512]
  comm.w_decay: [0.001, 0.00001]
  comm.bn_decay: [0.9, 0.99]
  optim.lb_smooth: [0, 0.5]
