# 003_cifar_label_smoothing
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 500
method:
  base: sup
  is_mpl: False
optim:
  lb_smooth: 0.14
batch_size:
  sup: 128
  # uns: 128
  test: 128
stdn:
  lr: 0.25
  dropout: 0.03
tune:
  # stdn.lr: [0.001, 1.0]
  # stdn.dropout: [0, 1]
  # optim.momentum: [0.5, 0.999]
  optim.lb_smooth: [0, 0.5]
  # comm.w_decay: [0.001, 0.00001]
  # comm.bn_decay: [0.5, 0.999]
