# 004_cifar_10_randaugment.yaml
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 500
method:
  base: ra
  is_mpl: False
batch_size:
  sup: 128
  # uns: 128
  test: 128
stdn:
  lr: 0.3
  dropout: 0.35
randaug:
  n: 3
  m: 4
tune:
  stdn.lr: [0.001, 1.0]
  stdn.dropout: [0, 1]
  optim.momentum: [0.5, 0.999]
  # batch_size.sup: [64, 512]
  comm.w_decay: [0.001, 0.00001]
  comm.bn_decay: [0.5, 0.999]
  randaug.n: [1, 15]
  randaug.m: [1, 20]
