# 040_cifar10_uda.yaml
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 500
method:
  base: uda
  is_mpl: False
optim:
  momentum: 0.5424370614735192
comm:
  bn_decay: 0.8763891522960383
  w_decay: 0.00011433940313119117
batch_size:
  sup: 128   # 64
  uns: 128  # 64 * 7 (updated in the official code on 3 Feb)
  test: 128
stdn:
  lr: 0.17066058914500434
  dropout: 0.03905478323288236
uda:
  factor: 0.983468338330501
  tsa_schedule: ''  # ['', ''linear', 'log', 'exp']  # for labeled loss
  confid_threshold: 0.8781425034294131   # for unlabeled target dist.
  softmax_temp: 0.42110762500505217      # for unlabeled predicted dist.
tune:
  stdn.lr: [0.001, 1.0]
  stdn.dropout: [0, 1]
  optim.momentum: [0.5, 0.999]
  # batch_size.sup: [64, 512]
  comm.w_decay: [0.001, 0.00001]
  comm.bn_decay: [0, 1]
  uda.factor: [0, 10]
  uda.confid_threshold: [0, 1]
  uda.softmax_temp: [0, 1]
