# 040_cifar10_uda.yaml
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 500
method:
  base: uda
  is_mpl: False
optim:
  momentum: 0.8452466798612862
comm:
  bn_decay: 0.9578895301505019
  w_decay: 0.00047216636787671313
batch_size:
  sup: 128   # 64
  uns: 128  # 64 * 7 (updated in the official code on 3 Feb)
  test: 128
stdn:
  lr: 0.686814426753902
  dropout: 0.31551563100606295
uda:
  factor: 0.18288277344191806
  tsa_schedule: ''  # ['', ''linear', 'log', 'exp']  # for labeled loss
  confid_threshold: 0.8346256718973729   # for unlabeled target dist.
  softmax_temp: 0.7501443149449675      # for unlabeled predicted dist.
tune:
  stdn.lr: [0.001, 1.0]
  stdn.dropout: [0, 1]
  optim.momentum: [0.5, 0.999]
  # batch_size.sup: [64, 512]
  comm.w_decay: [0.001, 0.00001]
  comm.bn_decay: [0, 1]
  uda.factor: [0, 10]
  uda.confid_threshold: [0, 1]
  uda.softmax_temp: [0, 1]
