# 005_cifar10_uda.yaml
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 200
method:
  base: uda
  is_mpl: False
batch_size:
  sup: 64   # 64
  uns: 448  # 64 * 7 (updated in the official code on 3 Feb)
  test: 128
stdn:
  lr: 0.03
  dropout: 0.0  # no dropout
uda:
  factor: 1.0
  tsa_schedule: 'linear'  # ['', ''linear', 'log', 'exp']  # for labeled loss
  confid_threshold: 0.8   # for unlabeled target dist.
  softmax_temp: 0.4       # for unlabeled predicted dist.
