# 006_cifar10_supervised_mpl.yaml
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1 # in ['top1', 'loss']
  interval: 200
method:
  base: sup
  is_mpl: True
batch_size:
  sup: 128
  uns: 128
  test: 128
stdn:
  lr: 0.25
  dropout: 0.03
tchr:
  lr: 0.94
  dropout: 0.34
tune:
  # stdn.lr: [0.001, 1.0]
  tchr.lr: [0.001, 1.0]
  # stdn.dropout: [0, 1]
  tchr.dropout: [0, 1]
  # optim.momentum: [0.5, 0.999]
  # batch_size.sup: [64, 512]
  # batch_size.uns: [64, 512]
  # comm.w_decay: [0.001, 0.00001]
  # comm.bn_decay: [0.5, 0.999]
