# 060_cifar_10_randaugment.yaml
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 500
method:
  base: ra
  is_mpl: True
optim:
  momentum: 0.7128109194621965
comm:
  n_steps: 100000  
  bn_decay: 0.5172675985011298
  w_decay: 9.27582054766412e-05
batch_size:
  sup: 128
  uns: 128
  test: 128
stdn:
  lr: 0.3
  dropout: 0.35
tchr:
  lr: 0.125
  dropout: 0.5
randaug:
  n: 3
  m: 4
tune:
  stdn.lr: [0.001, 1.0]
  tchr.lr: [0.001, 1.0]
  stdn.dropout: [0, 1]
  tchr.dropout: [0, 1]
  optim.momentum: [0.5, 0.999]
  # batch_size.sup: [64, 512]
  comm.w_decay: [0.001, 0.00001]
  comm.bn_decay: [0, 1]
  # randaug.n: [1, 15]
  # randaug.m: [1, 20]
