# 008_cifar10_uda_mpl.yaml
model: wresnet_28_2
dataset: cifar10
n_labeled: 4000
valid:
  metric: top1
  interval: 200
method:
  base: uda
  is_mpl: True
batch_size:
  sup: 128
  uns: 128
  test: 128
stdn:
  lr: 0.3
  dropout: 0.35
tchr:
  lr: 0.125
  dropout: 0.5
uda:
  factor: 1.0
  tsa_schedule: 'linear'  # ['', ''linear', 'log', 'exp']  # for labeled loss
  confid_threshold: 0.8   # for unlabeled target dist.
  softmax_temp: 0.4       # for unlabeled predicted dist.
